version: '3.8'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.10.1
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"name\":\"clean\", \"variables\":[]}, {\"name\":\"rollvolet\", \"variables\":[]}]"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  frontend:
    image: rollvolet/frontend-price-management:1.3.0
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  project-scripts:
    image: semtech/simple-script-store:1.0.0
    volumes:
      - ./config/project-scripts/:/app/scripts/
    restart: "no"
    logging: *default-logging
    labels:
      - "logging=true"
  database:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  triplestore:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/rollvolet"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./config/db/:/opt/virtuoso-scripts
      - ./data/db:/data
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.3.0
    volumes:
      - ./config/delta:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  msal-login:
    image: rollvolet/msal-login-service:1.0.0
    environment:
      AUTH_REFRESH_TOKENS: "true"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  token-cache:
    image: redis:6.2.6
    volumes:
      - ./data/token-cache:/data
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  registration:
    image: semtech/mu-registration-service:2.7.3
    entrypoint: echo "Only needed for mu script"
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: "no"
    logging: *default-logging
    labels:
      - "logging=true"
  mock-login:
    image: semtech/mu-login-service:3.0.0
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  search:
    image: semtech/mu-search:0.10.0-beta.4
    volumes:
      - ./config/search:/config
    environment:
     JRUBY_OPTIONS: "-J-Xmx4g"
     NUMBER_OF_THREADS: 16
     LOG_LEVEL: "info"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  elasticsearch:
    image: semtech/mu-search-elastic-backend:1.1.0
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - JRUBY_OPTIONS="-Xms4g Xmx4g"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource:
    image: semtech/mu-cl-resources:1.23.0
    volumes:
      - ./config/resources:/config
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  file:
    image: semtech/mu-file-service:3.3.2
    volumes:
      - ./data/files:/share
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  sequence-numbers:
    image: rollvolet/sequence-numbers-service:0.1.0
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
