version: '3.8'

services:
  identifier:
    image: semtech/mu-identifier:1.9.0
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"rollvolet\"}]"
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    volumes:
      - ./config/dispatcher:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    volumes:
      - ./config/migrations:/data/migrations
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
  resource:
    image: semtech/mu-cl-resources:1.20.0
    volumes:
      - ./config/resources:/config
  file:
    image: semtech/mu-file-service:3.1.2
    volumes:
      - ./data/files:/share
