version: '3.8'

services:
  identifier:
    image: semtech/mu-identifier:1.9.0
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    volumes:
      - ./config/dispatcher:/config
  database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
  resource:
    image: semtech/mu-cl-resources:feature-json-documentation
    volumes:
      - ./config/resources:/config
