PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/rollvolet> {
    ?s ?p ?o
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/rollvolet> {
    ?s ?p ?newO
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/rollvolet> {
    ?s ?p ?o
  }
  FILTER(DATATYPE(?o) = xsd:boolean)
  BIND(STRDT(STR(?o), <http://mu.semte.ch/vocabularies/typed-literals/boolean>) as ?newO)
}
