PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/users> {
    <http://data.rollvolet.be/user-groups/employee> foaf:member ?user .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/users> {
    ?user a foaf:Person .
  }
}

;

INSERT {
  GRAPH <http://mu.semte.ch/graphs/users> {
    <http://data.rollvolet.be/user-groups/price-admin> foaf:member ?user .
    <http://data.rollvolet.be/user-groups/admin> foaf:member ?user .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/users> {
    ?user a foaf:Person ; foaf:name "Erika Pauwels"
  }
}
