(define-resource task ()
  :class (s-prefix "task:Task")
  :properties `((:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:status :url ,(s-prefix "adms:status"))
                (:operation :url ,(s-prefix "task:operation"))
                (:index :string ,(s-prefix "task:index")))
  :has-many `((task :via ,(s-prefix "cogs:dependsOn")
                    :as "parent-tasks"))
  :has-one `((data-container :via ,(s-prefix "task:resultContainer")
                   :as "result-container")
             (data-container :via ,(s-prefix "task:inputContainer")
                   :as "input-container")
             )
  :resource-base (s-url "http://data.rollvolet.be/tasks/")
  :features '(include-uri)
  :on-path "tasks")

(define-resource data-container ()
  :class (s-prefix "nfo:DataContainer")
  :has-one `((task :via ,(s-prefix "task:resultContainer")
                    :inverse t
                    :as "result-from-tasks")
              (task :via ,(s-prefix "task:inputContainer")
                    :inverse t
                    :as "input-from-tasks"))
  :has-many `((file :via ,(s-prefix "ext:content")
                    :as "files")
              )
  :resource-base (s-url "http://data.rollvolet.be/data-containers/")
  :features '(include-uri)
  :on-path "data-containers")
